# Generated by Django 3.0.3 on 2020-02-22 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cowsay',
            old_name='contents',
            new_name='text',
        ),
    ]
