# Generated by Django 3.0.3 on 2020-03-31 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay', '0002_auto_20200222_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowsay',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
